# 🔹 ALT + Key → Open in Firefox
bind = ALT, i, exec, firefox --new-tab "https://monkeytype.com/"
bind = ALT, p, exec, firefox --new-tab "https://hentaifox.com/"
bind = ALT, n, exec, firefox --new-tab "https://nyaa.si/"
bind = ALT, d, exec, firefox --new-tab "https://discord.com/channels/@me"
bind = ALT, u, exec, firefox --new-tab "https://makaut1.ucanapply.com/smartexam/public/"
bind = ALT, b, exec, firefox --new-tab "https://myanimelist.net/profile/PaulSteve"
bind = ALT, e, exec, firefox --new-tab "http://moodlebppimt.ddns.net/login/index.php"
bind = ALT, g, exec, firefox --new-tab "https://www.cloudskillsboost.google/"
# bind = ALT, m, exec, firefox --new-tab "https://open.spotify.com/"
# bind = ALT, w, exec, firefox --new-tab "https://web.whatsapp.com/"
# bind = ALT, y, exec, firefox --new-tab "https://youtube.com/"
# bind = ALT, c, exec, firefox --new-tab "https://chatgpt.com/"


bind = ALT, Y, exec, hyprctl dispatch workspace 10 && firefox --new-window https://www.youtube.com && sleep 0.2 && hyprctl dispatch tagwindow +youtube && hyprctl dispatch fullscreenstate 0 2
bind = ALT, m, exec, hyprctl dispatch workspace 8 && firefox --new-window https://open.spotify.com && sleep 0.2 && hyprctl dispatch tagwindow +spotify && hyprctl dispatch fullscreenstate 0 2
bind = ALT, w, exec, hyprctl dispatch workspace 9 && firefox --new-window https://web.whatsapp.com && sleep 0.2 && hyprctl dispatch tagwindow +whatsapp && hyprctl dispatch fullscreenstate 0 2
bind = ALT, C, exec, hyprctl dispatch workspace special:ai && firefox --new-window https://chat.openai.com && sleep 0.2 && hyprctl dispatch tagwindow +ai && hyprctl dispatch fullscreenstate 0 2


# 🔹 ALT + SHIFT + Key → Open in Chromium
bind = ALT SHIFT, w, exec, chromium --new-tab "https://web.whatsapp.com/"
bind = ALT SHIFT, y, exec, chromium --new-tab "https://youtube.com/"
bind = ALT SHIFT, i, exec, chromium --new-tab "https://monkeytype.com/"
bind = ALT SHIFT, p, exec, chromium --new-tab "https://hentaifox.com/"
bind = ALT SHIFT, n, exec, chromium --new-tab "https://nyaa.si/"
bind = ALT SHIFT, m, exec, chromium --new-tab "https://open.spotify.com/"
bind = ALT SHIFT, d, exec, chromium --new-tab "https://discord.com/channels/@me"
bind = ALT SHIFT, u, exec, chromium --new-tab "https://makaut1.ucanapply.com/smartexam/public/"
bind = ALT SHIFT, c, exec, chromium --new-tab "https://chatgpt.com/"
bind = ALT SHIFT, b, exec, chromium --new-tab "https://myanimelist.net/profile/PaulSteve"
bind = ALT SHIFT, e, exec, chromium --new-tab "http://moodlebppimt.ddns.net/login/index.php"
bind = ALT SHIFT, g, exec, firefox --new-tab "https://www.cloudskillsboost.google/"
