# 🔹 ALT + Key → Open in Firefox
bind = ALT, w, exec, firefox --new-tab "https://web.whatsapp.com/"
bind = ALT, y, exec, firefox --new-tab "https://youtube.com/"
bind = ALT, i, exec, firefox --new-tab "https://monkeytype.com/"
bind = ALT, p, exec, firefox --new-tab "https://hentaifox.com/"
bind = ALT, n, exec, firefox --new-tab "https://nyaa.si/"
bind = ALT, m, exec, firefox --new-tab "https://open.spotify.com/"
bind = ALT, d, exec, firefox --new-tab "https://discord.com/channels/@me"
bind = ALT, u, exec, firefox --new-tab "https://makaut1.ucanapply.com/smartexam/public/"
bind = ALT, c, exec, firefox --new-tab "https://chatgpt.com/"
bind = ALT, b, exec, firefox --new-tab "https://myanimelist.net/profile/PaulSteve"
bind = ALT, e, exec, firefox --new-tab "http://moodlebppimt.ddns.net/login/index.php"
bind = ALT, g, exec, firefox --new-tab "https://www.cloudskillsboost.google/"

# 🔹 ALT + SHIFT + Key → Open in Chromium
bind = ALT SHIFT, w, exec, chromium --new-tab "https://web.whatsapp.com/"
bind = ALT SHIFT, y, exec, chromium --new-tab "https://youtube.com/"
bind = ALT SHIFT, i, exec, chromium --new-tab "https://monkeytype.com/"
bind = ALT SHIFT, p, exec, chromium --new-tab "https://hentaifox.com/"
bind = ALT SHIFT, n, exec, chromium --new-tab "https://nyaa.si/"
bind = ALT SHIFT, m, exec, chromium --new-tab "https://open.spotify.com/"
bind = ALT SHIFT, d, exec, chromium --new-tab "https://discord.com/channels/@me"
bind = ALT SHIFT, u, exec, chromium --new-tab "https://makaut1.ucanapply.com/smartexam/public/"
bind = ALT SHIFT, c, exec, chromium --new-tab "https://chatgpt.com/"
bind = ALT SHIFT, b, exec, chromium --new-tab "https://myanimelist.net/profile/PaulSteve"
bind = ALT SHIFT, e, exec, chromium --new-tab "http://moodlebppimt.ddns.net/login/index.php"
bind = ALT SHIFT, g, exec, firefox --new-tab "https://www.cloudskillsboost.google/"
