$mainMod = SUPER
$fileManager = thunar

#power-and sleepp
bindl = CTRL ALT, DOWN, exec, systemctl poweroff     #sleep
bindl = CTRL ALT, LEFT, exec, hyprctl dispatch exit  #logout
bind = CTRL ALT, RIGHT, exec, hyprlock              #lock
bind = ALT, F4, exec, sh -c 'asusctl profile next; profile=$(asusctl profile get | awk -F": " "/Active profile/ {print \$2}"); notify-send -r 8888 -h string:x-dunst-stack-tag:no -t 1000 "$profile"'
bind = SUPER, grave, exec, ~/.config/scripts/toggleMode.sh


#trminal
bind = $mainMod, Return, exec, foot
bind = SUPER_SHIFT, RETURN, exec, alacritty 

#TUI
bind =  SUPER, Y, exec, foot -e btop
bind =  SUPER SHIFT, Y, exec, foot -e termusic

##AltClipboard
# bind = CTRL SHIFT, C, exec, ~/.local/bin/store_alt_clip.sh


bind = $mainMod, E, exec, $fileManager
bind = $mainMod SHIFT, E, exec, foot -e yazi 
# bind = $mainMod, B, exec, sh -c "GDK_DPI_SCALE=0.75 firefox"
bind = $mainMod, B, exec, brave --force-device-scale-factor=0.85 --profile-directory="Default"
bind = $mainMod SHIFT, B, exec, sh -c "chromium"
bind = $mainMod, D, exec, vesktop
bind = $mainMod, T, exec, ~/.config/scripts/Telegram.sh
bind = SUPER SHIFT, grave, exec, ~/.config/scripts/toggleBluetooth.sh
bind = $mainMod, O, exec, prime-run gamemoderun /home/paul/Games/osu.AppImage


bind = $mainMod, Z, exec, ~/.config/scripts/waybar.sh
bind = SUPER, PAUSE,exec, ~/.config/scripts/roll.sh
bind=SUPER CTRL,C,exec,~/.config/scripts/wallcycle.sh

#bemenu stuff
bind = $mainMod, SPACE, exec, ~/.config/scripts/launcher.sh         #generic program launcher
bind = $mainMod SHIFT, SPACE, exec, ~/.config/scripts/cliphish.sh   #cliphist picker
bind = ALT SHIFT,SPACE,exec,~/.config/scripts/choice.sh             #read you know what  :))
bind = CTRL ALT,SPACE,exec,~/.config/scripts/read.sh                #link choice 
bind = SUPER, Period, exec, ~/.config/scripts/emoji.sh -t           #emoji picker
bind = SUPER, backslash, exec, ~/.config/scripts/adToChoice.sh
bind = SUPER, G, exec, ~/.config/scripts/game.sh


#kdeconnectd
bind = $mainMod, UP, exec, kdeconnect-cli -d $(kdeconnect-cli -a --id-only) --send-clipboard
bind = $mainMod, HOME, exec, pkill kdeconnectd ; kdeconnectd

#Screenshot
bind = , Print, exec, grim -g "$(slurp -b 000000AA -c 263238FF)" - | tee ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png | wl-copy #regional ss
bind = SUPER, Print, exec, grim - | tee ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png | wl-copy  #full screen ss
bind = CTRL, Print, exec, flameshot gui -c -p $HOME/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png


#nmcli
bindl = $mainMod, Q, exec, nmcli device wifi rescan

# move window by pixel
bind = SUPER ALT, h, exec, ~/.config/scripts/move.sh left
bind = SUPER ALT, l, exec, ~/.config/scripts/move.sh right
bind = SUPER ALT, k, exec, ~/.config/scripts/move.sh up
bind = SUPER ALT, j, exec, ~/.config/scripts/move.sh down

## to port binds
# minecraft launch

##VM
# toggle into VM mode
bind = SUPER, F12, submap, vm

submap = vm

# exit VM mode
bind = SUPER, F12, submap, reset

# optional indicator
bind = SUPER, Escape, submap, reset

submap = reset
bind = SUPER, F1, exec, ~/.local/share/study/study.sh
