$mainMod = SUPER
$fileManager = thunar

#power-and sleepp
bind = CTRL ALT, DOWN, exec, systemctl poweroff     #sleep
bind = CTRL ALT, LEFT, exec, hyprctl dispatch exit  #logout
bind = CTRL ALT, RIGHT, exec, hyprlock              #lock
bind = ALT, F4, exec, asusctl profile -n;notify-send -r 8888 -h string:x-dunst-stack-tag:no -t 1000 "$(asusctl profile -p | grep 'Active' | cut -d ' ' -f 4-)"  #:Todo refactor it to be crossplatform

#trminal
bind = $mainMod, Return, exec, hyprctl keyword windowrulev2 "workspace unset, class:^(foot)$" && foot
bind = SUPER_SHIFT, RETURN, exec, hyprctl keyword windowrulev2 "workspace special:magic, class:^(foot)$" && foot -e fish -c "fastfetch & exec fish"  #:Todo fix it later

#TUI
bind =  SUPER, T, exec, foot -e btop
bind =  SUPER SHIFT, T, exec, foot -e termusic


bind = $mainMod, E, exec, $fileManager
bind = $mainMod, B, exec, sh -c "GDK_DPI_SCALE=0.75 firefox"
bind = $mainMod SHIFT, B, exec, sh -c "chromium --force-device-scale-factor=0.75"
bind = $mainMod, D, exec, discord
bind = $mainMod, X, exec, cpupower-gui
bind = $mainMod, N, exec, miru
bind = $mainMod, O, exec, gamemode-run /home/paul/Games/osu.AppImag


bind = $mainMod, Z, exec, ~/.config/scripts/waybar.sh
bind = SUPER, PAUSE,exec, ~/.config/scripts/roll.sh
bind=SUPER CTRL,C,exec,~/.config/scripts/wallcycle.sh

#bemenu stuff
bind = $mainMod, SPACE, exec, ~/.config/scripts/launcher.sh         #generic program launcher
bind = $mainMod SHIFT, SPACE, exec, ~/.config/scripts/cliphish.sh   #cliphist picker
bind = ALT SHIFT,SPACE,exec,~/.config/scripts/choice.sh                #read you know what  :))
bind = CTRL ALT,SPACE,exec,~/.config/scripts/read.sh              #link choice 


#kdeconnectd
bind = $mainMod, UP, exec, kdeconnect-cli -d $(kdeconnect-cli -a --id-only) --send-clipboard
bind = $mainMod, HOME, exec, pkill kdeconnectd ; kdeconnectd

#Screenshot
bind = , Print, exec, grim -g "$(slurp -b 000000AA -c 902DF3FF)" - | tee ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png | wl-copy #regional ss
bind = SUPER, Print, exec, grim - | tee ~/Pictures/Screenshots/$(date +'%Y-%m-%d_%H-%M-%S').png | wl-copy  #full screen ss


#nmcli
bind = $mainMod, Q, exec, nmcli device wifi rescan



## to port binds
# minecraft launch
