##############################
### WINDOWS AND WORKSPACES ###
##############################

# Set opacity for specific apps
# windowrulev2 = opacity 0.95 override,class:^(firefox)$,title:.*
windowrulev2 = opacity 0.95 override,class:^(wpp)$,title:.*
windowrulev2 = opacity 0.95 override,class:^(wps)$,title:.*
windowrulev2 = opacity 1.0 override,fullscreen:1,title:.*       # Fullscreen windows should be fully opaque

# Set specific apps to always open on certain workspaces
windowrule = match:class firefox, workspace 1, opaque on
windowrule = match:class chromium, workspace 2
windowrule = match:class vesktop, workspace 4,opacity 0.9
windowrule = match:class osu, workspace 5,opaque on
windowrule = match:class org.qbittorrent.qBittorrent, workspace 6
windowrule = match:title Picture-in-Picture, pin 1, float 1, size 502 284, move 1414 792,no_initial_focus on,opaque on,border_size 0 # firefox Picture-in-Picture sticky bit


# stock
# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


windowrulev2 = float, class:^(org.kde.kdeconnect.handler)$,title:.*  # KDE Connect share window

# KDE Connect presentation pointer window
windowrulev2 = float,class:^(org.kde.kdeconnect.daemon)$
windowrulev2 = size 1920 1080 ,class:^(org.kde.kdeconnect.daemon)$
# windowrulev2 = move 0% 0%,class:^(org.kde.kdeconnect.daemon)$
windowrulev2 = nofocus,class:^(org.kde.kdeconnect.daemon)$
windowrulev2 = pin,class:^(org.kde.kdeconnect.daemon)$

