##############################
### WINDOWS AND WORKSPACES ###
##############################

# Set opacity for specific apps
# windowrulev2 = opacity 0.95 override,class:^(firefox)$,title:.*
# windowrulev2 = opacity 0.95 override,class:^(wpp)$,title:.*
# windowrulev2 = opacity 0.95 override,class:^(wps)$,title:.*
windowrule = match:fullscreen on, opaque on

# Set specific apps to always open on certain workspaces
windowrule = match:class firefox, opaque on
windowrule = match:class brave-.*, opaque on
windowrule = match:class foot , opacity 0.85
windowrule = match:class org.pwmt.zathura, opacity 0.9
windowrule = match:class chromium, workspace 2
windowrule = match:class steam, workspace 6
windowrule = match:class vesktop, workspace 4,opacity 0.95
windowrule = match:class osu, workspace 5,opaque on
windowrule = match:class org.qbittorrent.qBittorrent, workspace 6
windowrule = match:title ^Picture-in-Picture$, pin 1, float 1, size 502 284, move 1414 792,no_initial_focus on,opaque on,border_size 0 # firefox Picture-in-Picture sticky bit
windowrule {
  name = pip-window
  match:title = ^Picture in picture$

  pin = on
  float = on
  size = 502 284
  move = 1414 792
  no_initial_focus = on
  opaque = on
  border_size = 0
}

windowrule = match:initial_class ^brave-ponfpcnoihfmfllpaingbgckeeldkhle-Default$, pin 1, float 1, size 502 284, move 1414 792, no_initial_focus on, opaque on, border_size 0



# stock
# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppress_event maximize, match:class .
# windowrulev2 = suppressevent maximize, class:.*


# windowrulev2 = float, class:^(org.kde.kdeconnect.handler)$,title:.*  # KDE Connect share window
windowrule = match:title ^org.kde.kdeconnect.handler$,float 1

# KDE Connect
windowrule = match:initial_title ^Receiving files — KDE Connect Daemon$, float 1 , size 502 284
windowrule = match:initial_title ^KDE Connect Daemon$,float on, size 1920 1080 , move 0 0, no_initial_focus on, pin on 

#webapps

windowrule = workspace 10, match:initial_class ^brave-youtube\.com__-Profile_1$
windowrule = workspace 8, match:initial_class ^brave-spotify\.com__-Profile_1$
windowrule = workspace 9,opacity 0.95, match:initial_class ^brave-web\.whatsapp\.com__-Profile_1$
windowrule = opaque on, match:class io.github.tdesktop_x64.TDesktop
windowrule = workspace 5, match:initial_class ^brave-paper2gal.com__-Profile_1$
windowrule = workspace special:ai, match:initial_class ^brave-chat\.openai\.com__-Profile_1$

