##############################
### WINDOWS AND WORKSPACES ###
##############################

# Set opacity for specific apps
windowrulev2 = opacity 0.95 override,class:^(firefox)$,title:.*
windowrulev2 = opacity 0.95 override,class:^(wpp)$,title:.*
windowrulev2 = opacity 0.95 override,class:^(wps)$,title:.*
windowrulev2 = opacity 1.0 override,fullscreen:1,title:.*       # Fullscreen windows should be fully opaque

# Set specific apps to always open on certain workspaces
windowrulev2 = workspace 1, class:^(firefox)$
windowrulev2 = workspace 3, class:^(chromium)$
windowrulev2 = workspace 4, class:^(vesktop)$,title:.*
windowrulev2 = workspace 5, class:^(osu!)$
windowrulev2 = workspace 6, class:^(org.qbittorrent.qBittorrent)$

# stock
# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


windowrulev2 = float, class:^(org.kde.kdeconnect.handler)$,title:.*  # KDE Connect share window

# KDE Connect presentation pointer window
windowrulev2 = float,class:^(org.kde.kdeconnect.daemon)$
windowrulev2 = size 1920 1080 ,class:^(org.kde.kdeconnect.daemon)$
# windowrulev2 = move 0% 0%,class:^(org.kde.kdeconnect.daemon)$
windowrulev2 = nofocus,class:^(org.kde.kdeconnect.daemon)$
windowrulev2 = pin,class:^(org.kde.kdeconnect.daemon)$

